
const RINKEBY = 'rinkeby'
const KOVAN = 'kovan'
const MAINNET = 'mainnet'
const LOCALHOST = 'localhost'
const ESSENTIA = 'essentia'

const MAINNET_CODE = 1
const RINKEYBY_CODE = 4
const KOVAN_CODE = 42
const ESSENTIA_CODE = 5678

const ROPSTEN_DISPLAY_NAME = 'Ropsten'
const ESSENTIA_DISPLAY_NAME = 'Essentia Test Network'
const RINKEBY_DISPLAY_NAME = 'Rinkeby'
const KOVAN_DISPLAY_NAME = 'Kovan'
const MAINNET_DISPLAY_NAME = 'Main Ethereum Network'

module.exports = {
  ESSENTIA,
  RINKEBY,
  KOVAN,
  MAINNET,
  LOCALHOST,
  ESSENTIA,
  MAINNET_CODE,
    ESSENTIA_CODE,
  RINKEYBY_CODE,
  KOVAN_CODE,
  ESSENTIA_CODE,
  ROPSTEN_DISPLAY_NAME,
  RINKEBY_DISPLAY_NAME,
  KOVAN_DISPLAY_NAME,
  MAINNET_DISPLAY_NAME,
  ESSENTIA_DISPLAY_NAME
}
