
const RINKEBY = 'rinkeby'
const KOVAN = 'kovan'
const MAINNET = 'mainnet'
const LOCALHOST = 'localhost'
const ESSENTIA = 'essentia'
const ESSENTIAMAINNET = 'essentiaMainnet'
const ROPSTEN = 'ropsten'
const ESSENTIA_RPC_URL = 'http://18.217.38.48:8545'
const ESSENTIAMAINNET_RPC_URL = 'http://18.224.247.56:8545'

const MAINNET_CODE = 1
const RINKEYBY_CODE = 4
const KOVAN_CODE = 42
const ESSENTIA_CODE = 5678
const ESSENTIAMAINNET_CODE = 4201
const ROPSTEN_CODE = 3

const ROPSTEN_DISPLAY_NAME = 'Ropsten'
const ESSENTIA_DISPLAY_NAME = 'Essentia Test Network'
const ESSENTIAMAINNET_DISPLAY_NAME = 'Main Essentia Network'
const RINKEBY_DISPLAY_NAME = 'Rinkeby'
const KOVAN_DISPLAY_NAME = 'Kovan'
const MAINNET_DISPLAY_NAME = 'Main Ethereum Network'

module.exports = {
  ROPSTEN,
  ESSENTIA,
  ESSENTIAMAINNET,
  RINKEBY,
  KOVAN,
  MAINNET,
  LOCALHOST,
  MAINNET_CODE,
  RINKEYBY_CODE,
  KOVAN_CODE,
  ESSENTIA_CODE,
  ESSENTIAMAINNET_CODE,
  ROPSTEN_CODE,
  ROPSTEN_DISPLAY_NAME,
  RINKEBY_DISPLAY_NAME,
  KOVAN_DISPLAY_NAME,
  MAINNET_DISPLAY_NAME,
  ESSENTIA_DISPLAY_NAME,
  ESSENTIAMAINNET_DISPLAY_NAME,
  ESSENTIAMAINNET_RPC_URL,
  ESSENTIA_RPC_URL,
}
